sonar.projectKey=nest-ape
sonar.projectName=nest-api
sonar.host.url=http://localhost:9000

sonar.sources=src,ai-service
sonar.exclusions=dist/**,node_modules/**,public/**,prisma/migrations/**,ai-service/__pycache__/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
