sonar.projectKey=ainya-unicap_nest-api
sonar.organization=ainya-unicap
sonar.projectName=nest-api

sonar.sources=src,ai-service
sonar.exclusions=dist/**,node_modules/**,public/**,prisma/migrations/**,ai-service/__pycache__/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
